export const dataPerubahanDTW = [
  {
    id: 0,
    namaDTW: 'Glamping Lakeside',
    kotaKab: 'Kab. Bandung',
    nib: '2003182400163',
    jenisDTW: 'Berkembang',
    namaPengelola: 'Lorem ipsum dolor amet blablablabla',
    statusPengajuan: 'pending',
  },
  {
    id: 1,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '2003182400163',
    jenisDTW: 'Berkembang',
    namaPengelola: 'Lorem ipsum dolor amet blablablabla',
    statusPengajuan: 'ditolak',
  },
];

export const dataPengajuanDTW = [
  {
    id: 0,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '2003182400163',
    jenisDTW: 'Berkembang',
    jenisPengajuan: 'Elemen DTW',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    namaPengelola: 'Lorem ipsum dolor amet blablablabla',
    statusPengajuan: 'diajukan',
  },
  {
    id: 1,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '2003182400163',
    jenisDTW: 'Berkembang',
    jenisPengajuan: 'Rencana Pengembangan',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    namaPengelola: 'Lorem ipsum dolor amet blablablabla',
    statusPengajuan: 'diverifikasi',
  },
  {
    id: 2,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '2003182400163',
    jenisDTW: 'Berkembang',
    jenisPengajuan: 'Elemen DTW',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    namaPengelola: 'Lorem ipsum dolor amet blablablabla',
    statusPengajuan: 'tervalidasi',
  },
  {
    id: 3,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '2003182400163',
    jenisDTW: 'Berkembang',
    jenisPengajuan: 'Pengendalian DTW',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    namaPengelola: 'Lorem ipsum dolor amet blablablabla',
    statusPengajuan: 'tervalidasi',
  },
  {
    id: 4,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '2003182400163',
    jenisDTW: 'Berkembang',
    jenisPengajuan: 'Pengendalian DTW',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    namaPengelola: 'Lorem ipsum dolor amet blablablabla',
    statusPengajuan: 'tervalidasi',
  },
  {
    id: 5,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '2003182400163',
    jenisDTW: 'Berkembang',
    jenisPengajuan: 'Rencana Pengembangan',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    namaPengelola: 'Lorem ipsum dolor amet blablablabla',
    statusPengajuan: 'tervalidasi',
  },
];

export const elementDTW = [
  {
    id: 0,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    jenisDTW: 'Berkembang',
    jenisPengajuan: 'Elemen DTW',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    namaPengelola: 'Lorem ipsum dolor amet blablablabla',
    statusPengajuan: 'draft',
  },
  {
    id: 1,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    jenisDTW: 'Berkembang',
    jenisPengajuan: 'Rencana Pengembangan',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    namaPengelola: 'Lorem ipsum dolor amet blablablabla',
    statusPengajuan: 'draft',
  },
  {
    id: 2,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    jenisDTW: 'Berkembang',
    jenisPengajuan: 'Elemen DTW',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    namaPengelola: 'Lorem ipsum dolor amet blablablabla',
    statusPengajuan: 'draft',
  },
  {
    id: 3,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    jenisDTW: 'Berkembang',
    jenisPengajuan: 'Pengendalian DTW',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    namaPengelola: 'Lorem ipsum dolor amet blablablabla',
    statusPengajuan: 'draft',
  },
  {
    id: 4,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    jenisDTW: 'Berkembang',
    jenisPengajuan: 'Pengendalian DTW',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    namaPengelola: 'Lorem ipsum dolor amet blablablabla',
    statusPengajuan: 'draft',
  },
  {
    id: 5,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    jenisDTW: 'Berkembang',
    jenisPengajuan: 'Rencana Pengembangan',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    namaPengelola: 'Lorem ipsum dolor amet blablablabla',
    statusPengajuan: 'draft',
  },
];

export const dataDTW = [
  {
    id: 1,
    namaDTW: 'Glamping Lakeside',
    kotaKab: 'Kab. Bandung',
    nib: '2003182400163',
    jenisDTW: 'Berkembang',
    namaPengelola: 'Lorem ipsum dolor amet blablablabla',
    statusCHSE: true,
  },
  {
    id: 2,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '2003182400163',
    jenisDTW: 'Berkembang',
    namaPengelola: 'Lorem ipsum dolor amet blablablabla',
    statusCHSE: true,
  },
  {
    id: 3,
    namaDTW: 'Tangkuban Perahu',
    kotaKab: 'kab. Bandung Barat',
    nib: '2003182400163',
    jenisDTW: 'Berkembang',
    namaPengelola: 'Lorem ipsum dolor amet blablablabla',
    statusCHSE: false,
  },
  {
    id: 4,
    namaDTW: 'Taman Safari',
    kotaKab: 'kab. Bogor',
    nib: '2003182400163',
    jenisDTW: 'Berkembang',
    namaPengelola: 'Lorem ipsum dolor amet blablablabla',
    statusCHSE: true,
  },
];

export const rencanaPengembangan = [
  {
    id: 0,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '0123456789',
    jenisDTW: 'Berkembang',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    statusCHSE: 'draft',
  },
  {
    id: 1,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '0123456789',
    jenisDTW: 'Berkembang',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    statusCHSE: 'draft',
  },
  {
    id: 2,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '0123456789',
    jenisDTW: 'Berkembang',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    statusCHSE: 'draft',
  },
  {
    id: 3,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '0123456789',
    jenisDTW: 'Berkembang',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    statusCHSE: 'draft',
  },
  {
    id: 4,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '0123456789',
    jenisDTW: 'Berkembang',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    statusCHSE: 'draft',
  },
  {
    id: 5,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '0123456789',
    jenisDTW: 'Berkembang',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    statusCHSE: 'draft',
  },
  {
    id: 6,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '0123456789',
    jenisDTW: 'Berkembang',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    statusCHSE: 'draft',
  },
  {
    id: 7,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '0123456789',
    jenisDTW: 'Berkembang',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    statusCHSE: 'draft',
  },
  {
    id: 8,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '0123456789',
    jenisDTW: 'Berkembang',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    statusCHSE: 'draft',
  },
  {
    id: 9,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '0123456789',
    jenisDTW: 'Berkembang',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    statusCHSE: 'draft',
  },
];

export const pengendalianDTW = [
  {
    id: 0,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '0123456789',
    jenisDTW: 'Berkembang',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    statusCHSE: 'draft',
    jenisPengendalian: 'Survey Harian',
  },
  {
    id: 1,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '0123456789',
    jenisDTW: 'Berkembang',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    statusCHSE: 'draft',
    jenisPengendalian: 'Survey Harian',
  },
  {
    id: 2,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '0123456789',
    jenisDTW: 'Berkembang',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    statusCHSE: 'draft',
    jenisPengendalian: 'Survey Harian',
  },
  {
    id: 3,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '0123456789',
    jenisDTW: 'Berkembang',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    statusCHSE: 'draft',
    jenisPengendalian: 'Survey Harian',
  },
  {
    id: 4,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '0123456789',
    jenisDTW: 'Berkembang',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    statusCHSE: 'draft',
    jenisPengendalian: 'Survey Harian',
  },
  {
    id: 5,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '0123456789',
    jenisDTW: 'Berkembang',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    statusCHSE: 'draft',
    jenisPengendalian: 'Survey Harian',
  },
  {
    id: 6,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '0123456789',
    jenisDTW: 'Berkembang',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    statusCHSE: 'draft',
    jenisPengendalian: 'Survey Harian',
  },
  {
    id: 7,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '0123456789',
    jenisDTW: 'Berkembang',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    statusCHSE: 'draft',
    jenisPengendalian: 'Survey Harian',
  },
  {
    id: 8,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '0123456789',
    jenisDTW: 'Berkembang',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    statusCHSE: 'draft',
    jenisPengendalian: 'Survey Harian',
  },
  {
    id: 9,
    namaDTW: 'Dago Pakar',
    kotaKab: 'Kota. Bandung',
    nib: '0123456789',
    jenisDTW: 'Berkembang',
    waktuPengajuan: '11:10:14 AM, Feb 10, 2022',
    statusCHSE: 'draft',
    jenisPengendalian: 'Survey Harian',
  },
];
