export const navListRencanaPembangunan = [
  {
    title: 'Pembangunan',
    path: '/rencana-pengembangan/buat-baru/pembangunan',
  },
  {
    title: 'Investasi',
    path: '/rencana-pengembangan/buat-baru/investasi',
  },
  {
    title: 'Dokumen Penunjang',
    path: '/rencana-pengembangan/buat-baru/dokumen-penunjang',
  },
];

export const navListSidebarEditProfile = [
  {
    icon: '/icon/pengaturan-akun-icon-white.svg',
    iconActive: '/icon/pengaturan-akun-icon-green.svg',
    title: 'Pengaturan Akun',
    path: '/profile/pengaturan-akun',
  },
  {
    icon: '/icon/password-icon-white.svg',
    iconActive: '/icon/password-icon-green.svg',
    title: 'Ubah Password',
    path: '/profile/ubah-password',
  },
];

export const navList = [
  {
    title: 'Aspek Umum',
    path: '/user/pelaporan-perkebunan/aspek-umum',
    icon: '/icon/home-icon-white.svg',
    isAdmin: true,
    stickyBot: false,
    arrowRight: false,
    // isActive: true,
  },
  {
    title: 'Aspek Manajemen',
    path: '/user/pelaporan-perkebunan/aspek-manajemen',
    icon: '/icon/home-icon-white.svg',
    isAdmin: true,
    stickyBot: false,
    arrowRight: false,
    // isActive: true,
  },
  {
    title: 'Aspek Kebun',
    path: '/user/pelaporan-perkebunan/aspek-kebun',
    icon: '/icon/home-icon-white.svg',
    isAdmin: true,
    stickyBot: false,
    arrowRight: false,
    // isActive: false,
  },
  {
    title: 'Aspek Pengolahan',
    path: '/user/pelaporan-perkebunan/aspek-pengolahan',
    icon: '/icon/home-icon-white.svg',
    isAdmin: true,
    stickyBot: false,
    arrowRight: false,
  },
  {
    title: 'Aspek Sosial Ekonomi dan Lingkungan',
    path: '/user/pelaporan-perkebunan/aspek-sosial',
    icon: '/icon/home-icon-white.svg',
    isAdmin: true,
    stickyBot: false,
    arrowRight: false,
    // isActive: false,
  },
  {
    title: 'Konfirmasi',
    path: '/user/pelaporan-perkebunan/konfirmasi',
    icon: '/icon/home-icon-white.svg',
    isAdmin: true,
    stickyBot: true,
    arrowRight: true,
    // isActive: false,
  },
];

export const navListPenilaianPerkebunan = [
  {
    title: 'Legalitas',
    path: '/user/penilaian-perkebunan/legalitas',
    icon: '/icon/home-icon-white.svg',
    isAdmin: true,
    stickyBot: false,
    arrowRight: false,
    // isActive: true,
  },
  {
    title: 'Manajemen',
    path: '/user/penilaian-perkebunan/manajemen',
    icon: '/icon/home-icon-white.svg',
    isAdmin: true,
    stickyBot: false,
    arrowRight: false,
    // isActive: true,
  },
  {
    title: 'Kebun',
    path: '/user/penilaian-perkebunan/kebun',
    icon: '/icon/home-icon-white.svg',
    isAdmin: true,
    stickyBot: false,
    arrowRight: false,
    // isActive: false,
  },
  {
    title: 'Pengolahan Hasil',
    path: '/user/penilaian-perkebunan/pengolahan',
    icon: '/icon/home-icon-white.svg',
    isAdmin: true,
    stickyBot: false,
    arrowRight: false,
  },
  {
    title: 'Sosial',
    path: '/user/penilaian-perkebunan/sosial',
    icon: '/icon/home-icon-white.svg',
    isAdmin: true,
    stickyBot: false,
    arrowRight: false,
    // isActive: false,
  },
  {
    title: 'Ekonomi Wilayah',
    path: '/user/penilaian-perkebunan/ekonomi',
    icon: '/icon/home-icon-white.svg',
    isAdmin: true,
    stickyBot: false,
    arrowRight: false,
    // isActive: false,
  },
  {
    title: 'Lingkungan',
    path: '/user/penilaian-perkebunan/lingkungan',
    icon: '/icon/home-icon-white.svg',
    isAdmin: true,
    stickyBot: false,
    arrowRight: false,
    // isActive: false,
  },
  {
    title: 'Pelaporan',
    path: '/user/penilaian-perkebunan/pelaporan',
    icon: '/icon/home-icon-white.svg',
    isAdmin: true,
    stickyBot: false,
    arrowRight: false,
    // isActive: false,
  },
  {
    title: 'Konfirmasi',
    path: '/user/penilaian-perkebunan/konfirmasi',
    icon: '/icon/home-icon-white.svg',
    isAdmin: true,
    stickyBot: true,
    arrowRight: true,
    // isActive: false,
  },
];
